### ISSUE TITLE
ESP webserver-websocket wifi -serial bridge

### ISSUE THREAD

**Issue by mkeyno** [Ladvien/ESPER#1]
sorry to open ticket for my question but honestly I couldn't figure out which part of your code would be help me out, actually I intend to use my special webserver-websocket program(Arduino IDE) in the ESP module to made Wifi -serial bridge with simple C# application , may I have your advice which part of source code would be helpful for me?
BR

**Comment by Ladvien** [comment]
Focus on the LumiHttpPeripheral.cs.  That's where you will find most of what will probably help.  

https://github.com/Ladvien/ESPER/blob/master/ESPER/LumiPeripheralManagement/LumiHttpPeripheral.cs

Also, I've extended this into a longer term project, which may be found here:

https://github.com/Ladvien/Lumi4/tree/master/Lumi4/LumiCommunication

There code linked above I'm actively developing and will probably have fewer bugs, while being more complete.
